package com.pranksterlab.core.voice

enum class VoiceCategory { ROBOT_TECH, FUNNY_CARTOON, CREEPY_SPOOKY, SILLY_PRANK }
data class VoicePreset(val id:String,val displayName:String,val category:VoiceCategory,val description:String,val pitch:Float,val speechRate:Float,val volume:Float,val toneStyle:String,val effectStyle:String,val intensityLevel:Int,val isSafeForRandomMode:Boolean)
object VoicePresetLibrary { val presets: List<VoicePreset> = listOf(
VoicePreset("glitch_bot","Glitch Bot",VoiceCategory.ROBOT_TECH,"Choppy neon machine banter",0.86f,1.05f,0.9f,"Digital","Bitcrush",3,true),VoicePreset("friendly_android","Friendly Android",VoiceCategory.ROBOT_TECH,"Helpful companion with smooth tone",1.02f,1f,0.95f,"Warm Synth","Clean",2,true),VoicePreset("broken_intercom","Broken Intercom",VoiceCategory.ROBOT_TECH,"Old PA speaker with dropouts",0.92f,0.92f,0.88f,"Compressed","Intercom",4,true),VoicePreset("space_announcer","Space Announcer",VoiceCategory.ROBOT_TECH,"Orbital station status broadcast",1.12f,0.95f,1f,"Command","Echo",3,true),VoicePreset("tiny_terminal","Tiny Terminal",VoiceCategory.ROBOT_TECH,"Mini processor squeak",1.35f,1.18f,0.82f,"High Synth","Crisp",2,true),VoicePreset("villain_computer","Villain Computer",VoiceCategory.ROBOT_TECH,"Dramatic AI monologue mode",0.78f,0.88f,0.96f,"Dark Synth","Reverb",5,false),
VoicePreset("tiny_goblin","Tiny Goblin",VoiceCategory.FUNNY_CARTOON,"Mischievous prank cave chatter",1.4f,1.1f,0.9f,"Nasal","Snappy",3,true),VoicePreset("angry_squirrel","Angry Squirrel",VoiceCategory.FUNNY_CARTOON,"Fast annoyed squeaks",1.45f,1.22f,0.87f,"Sharp","Chatter",4,true),VoicePreset("dramatic_hamster","Dramatic Hamster",VoiceCategory.FUNNY_CARTOON,"Tiny actor with huge emotion",1.32f,0.9f,0.95f,"Theatrical","Studio",3,true),VoicePreset("sneaky_gremlin","Sneaky Gremlin",VoiceCategory.FUNNY_CARTOON,"Whispery chaos gremlin",1.22f,1.04f,0.84f,"Whisper","Rustle",3,true),VoicePreset("confused_narrator","Confused Narrator",VoiceCategory.FUNNY_CARTOON,"Lost storyteller energy",1f,0.96f,0.92f,"Narrative","Flutter",2,true),VoicePreset("game_show_host","Game Show Host",VoiceCategory.FUNNY_CARTOON,"Big prize wheel hype",1.1f,1.14f,1f,"Hype","Sparkle",4,true),
VoicePreset("haunted_hallway","Haunted Hallway",VoiceCategory.CREEPY_SPOOKY,"Distant corridor ghost echo",0.74f,0.78f,0.8f,"Hollow","Echo",4,false),VoicePreset("basement_whisper","Basement Whisper",VoiceCategory.CREEPY_SPOOKY,"Low whispered suspense",0.7f,0.7f,0.76f,"Breathy","Reverb",5,false),VoicePreset("ghost_host","Ghost Host",VoiceCategory.CREEPY_SPOOKY,"Paranormal late-night host",0.82f,0.86f,0.85f,"Eerie","Hall",4,false),VoicePreset("creepy_doll","Creepy Doll",VoiceCategory.CREEPY_SPOOKY,"Broken toy recital",1.28f,0.75f,0.9f,"Childlike","Warp",5,false),VoicePreset("shadow_narrator","Shadow Narrator",VoiceCategory.CREEPY_SPOOKY,"Velvet menace narration",0.76f,0.82f,0.88f,"Low","Dark Hall",4,false),VoicePreset("slow_monster","Slow Monster",VoiceCategory.CREEPY_SPOOKY,"Massive lumbering dialogue",0.62f,0.68f,0.94f,"Heavy","Sub Echo",5,false),
VoicePreset("overexcited_coach","Overexcited Coach",VoiceCategory.SILLY_PRANK,"Too much gym class hype",1.16f,1.15f,1f,"Pushy","Crowd",4,true),VoicePreset("sarcastic_butler","Sarcastic Butler",VoiceCategory.SILLY_PRANK,"Dry polished sarcasm",0.94f,0.9f,0.9f,"Dry","Room",2,true),VoicePreset("sleepy_announcer","Sleepy Announcer",VoiceCategory.SILLY_PRANK,"Late shift public speaker",0.88f,0.72f,0.83f,"Drowsy","Soft",2,true),VoicePreset("mad_scientist","Mad Scientist",VoiceCategory.SILLY_PRANK,"Chaotic laboratory lecture",1.2f,1.08f,0.97f,"Cackling","Lab",4,true),VoicePreset("clown_radio","Clown Radio",VoiceCategory.SILLY_PRANK,"Circus FM voiceover",1.26f,1.04f,0.93f,"Boing","Spring",3,true),VoicePreset("awkward_dad_joke","Awkward Dad Joke",VoiceCategory.SILLY_PRANK,"Proud joke setup pause",1f,0.92f,0.92f,"Cheerful","Garage",1,true)
)}
